security:
    encoders:
        App\Entity\Admin:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        admin_login: 
            entity: 
                class: App\Entity\Admin
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin: 
            pattern: ^/
            anonymous: true

            provider: admin_login

            form_login:
                # road to login form ?
                login_path: admin_login
                # Where send data after submit ?
                check_path: admin_login
                # Where redirect after login ?
                default_target_path: admin_dashboard

            logout: 
                # Road for logout 
                path: admin_logout
                # where redirect after logout ?
                target: home

        main:
            anonymous: true            
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
